### ISSUE TITLE
Rebuild Fuzzware after modifications with minimal effort

### ISSUE THREAD

**Issue by B03901108** [fuzzware-fuzzer/fuzzware#3]
Hello,

I would like to locally modify some code in modeling/fuzzware_modeling/ and see how the modification affects Fuzzware. I have set up Fuzzware locally. Could you share some suggestions on how to compile modifications to Fuzzware with minimal effort?

My current plan is to run the setup.sh in modeling/. The fallback plan is to rerun install_local.sh, which I would like to avoid. I raise this issue due to the concern that trying out these plans carelessly may break my local Fuzzware. Thank you very much.

Best regards.

**Comment by Scepticz** [comment]
Hi B03901108,

you can just use setup.sh in modeling. This should keep everything just fine. :-)

Best
Tobias
